stages:
  - test
  - build
  - run

test:
  stage: test
  image: python:3.11-alpine
  before_script:
    - apk add --no-cache gcc musl-dev libffi-dev openssl-dev
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - pytest
  artifacts:
    when: always
    reports:
      junit: report.xml
    paths:
      - report.xml

build:
  stage: build
  script:
    - docker build -t ecom_demo:v1 .


run:
  stage: run
  script:
    - docker stop api || true
    - docker rm api || true
    - docker run --name api --env-file /home/admin/ecom_demo/.env -p 5000:5000 ecom_demo:v1
